version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/optifit backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/optifit app"
    schedule:
      interval: "weekly"
