name: Bug report
description: Report a bug to help us improve
labels: bug
body:
  - type: textarea
    attributes:
      label: Description
      description: Clearly describe the bug you encountered.
      placeholder: >
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem.
      placeholder: >
        Drag and drop or paste screenshots here.
