name: Feature request
description: Suggest a new idea or improvement
labels: enhancement
body:
  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      placeholder: >
        Briefly explain the issue or need that this feature would address.
  - type: textarea
    attributes:
      label: Proposed solution
      placeholder: >
        Describe the feature or change you'd like to see.
  - type: textarea
    attributes:
      label: Alternatives considered
      placeholder: >
        Have you thought of other ways to solve this?
  - type: textarea
    attributes:
      label: Extra context
      placeholder: >
        Add any other details, examples, or screenshots here.
