name: Flutter CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "optifit app/**"
  push:
    branches: [ main ]
    paths:
      - "optifit app/**"

jobs:
  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: optifit app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test
