name: Flutter CI

on:
  pull_request:
    paths:
      - "optifit app/**"
  push:
    branches: [ main ]
    paths:
      - "optifit app/**"

jobs:
  flutter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: optifit app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: flutter format --set-exit-if-changed .

      - name: Analyze code
        run: |
          flutter analyze > analyze_output.txt
          cat analyze_output.txt
          if grep -q "error •" analyze_output.txt; then
            echo "Analysis failed due to errors"
            exit 1
          fi

      - name: Run tests
        run: flutter test
